"""empty message

Revision ID: 0b778019b3e4
Revises: 6e49d65e89c2
Create Date: 2021-09-11 20:36:38.092463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b778019b3e4'
down_revision = '6e49d65e89c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(length=64), nullable=False))
    op.drop_column('admin', 'password_salt')
    op.drop_column('admin', 'password_hash')
    op.drop_column('item', 'password_salt')
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=False))
    op.drop_column('user', 'password_salt')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('user', sa.Column('password_salt', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('user', 'password')
    op.add_column('item', sa.Column('password_salt', mysql.VARCHAR(length=16), nullable=False))
    op.add_column('admin', sa.Column('password_hash', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('admin', sa.Column('password_salt', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
